baseURL = "https://0verdud3.github.io/wak-lab/"
languageCode = "de-de"
title = "WAK-Lab"
theme = "beautifulhugo"


[params]
  [params.author]
    name = "WAK-Lab"
    link = "https://www.wak-lab.org"

  description = "Verein und Hackerspace"
  logo = "images/logo.png"