baseURL = "https://0verdud3.github.io/wak-lab/"
languageCode = "de-de"
title = "WAK-Lab"
theme = "beautifulhugo"


[params]
author = "WAK-Lab"
description = "Verein und Hackerspace"
logo = "images/logo.png"
logoOnHome = true